version: "3.9"

services:
  db:
    image: postgres:16
    container_name: rinha-db
    restart: always
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinha
      POSTGRES_DB: rinha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rinha-net
      - payment-processor
#    deploy:
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: "120MB"

  api-1:
    image: annicoletti/rinha-router:latest
    container_name: rinha-router-api-1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rinha
      SPRING_DATASOURCE_USERNAME: rinha
      SPRING_DATASOURCE_PASSWORD: rinha
      PAYMENT_SERVICE_URL_DEFAULT: http://payment-processor-default:8080
      PAYMENT_SERVICE_URL_FALLBACK: http://payment-processor-fallback:8080
      SERVER_PORT: 8080
    networks:
      - rinha-net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: "165MB"

  api-2:
    image: annicoletti/rinha-router:latest
    container_name: rinha-router-api-2
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/rinha
      SPRING_DATASOURCE_USERNAME: rinha
      SPRING_DATASOURCE_PASSWORD: rinha
      PAYMENT_SERVICE_URL_DEFAULT: http://payment-processor-default:8080
      PAYMENT_SERVICE_URL_FALLBACK: http://payment-processor-fallback:8080
      SERVER_PORT: 8080
    networks:
      - rinha-net
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.70"
          memory: "165MB"

  nginx:
    image: nginx:alpine
    container_name: rinha-router-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - rinha-net
      - payment-processor
    depends_on:
      - api-1
      - api-2
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "20MB"

volumes:
  pgdata:

networks:
  rinha-net:
    driver: bridge
  payment-processor:
    external: true
