services:

  nginx:
    image: nginx:alpine
    container_name: rinha-router-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "6MB"

  db:
    image: postgres:16
    container_name: rinha-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "30MB"

  redis-service:
    image: redis:alpine
    container_name: rinha-redis
    ports:
      - "6379:6379"
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "6MB"

  api-1:
    image: annicoletti/rinha-router:latest
    container_name: rinha-router-api-1
    depends_on:
      - redis-service
      - db
      - nginx
    env_file:
      - .env
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "154MB"

  api-2:
    image: annicoletti/rinha-router:latest
    container_name: rinha-router-api-2
    depends_on:
      - redis-service
      - db
      - nginx
    env_file:
      - .env
    networks:
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "154MB"

volumes:
  pgdata:

networks:
  payment-processor:
    external: true
