services:
  db:
    image: postgres:16
    container_name: rinha-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - payment-processor
#    deploy:
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: "120MB"

  redis-service:
    image: redis:latest
    container_name: rinha-redis
    ports:
      - "6379:6379"
    networks:
      - payment-processor
#    deploy:
#      resources:
#        limits:
#          cpus: "0.5"
#          memory: "120MB"

  api-1:
    image: annicoletti/rinha-router:latest
    container_name: rinha-router-api-1
    depends_on:
      - redis-service
      - db
    env_file:
      - .env
    networks:
      - payment-processor
#    deploy:
#      resources:
#        limits:
#          cpus: "0.70"
#          memory: "150MB"

  api-2:
    image: annicoletti/rinha-router:latest
    container_name: rinha-router-api-2
    depends_on:
      - redis-service
      - db
    env_file:
      - .env
    networks:
      - payment-processor
#    deploy:
#      resources:
#        limits:
#          cpus: "0.70"
#          memory: "150MB"

  nginx:
    image: nginx:alpine
    container_name: rinha-router-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - payment-processor
#    depends_on:
#      - api-1
#      - api-2
#    deploy:
#      resources:
#        limits:
#          cpus: "0.1"
#          memory: "20MB"

volumes:
  pgdata:

networks:
  payment-processor:
    external: true
