server:
  port: 9999

spring:
  application:
    name: rinha-router
  datasource:
    url: jdbc:postgresql://localhost:5432/rinha
    username: rinha
    password: rinha
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
