server:
  port: 9999

spring:
  application:
    name: rinha-router
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rinha}
    username: rinha
    password: rinha
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

payment:
  service:
    url:
      default: ${PAYMENT_SERVICE_URL_DEFAULT:http://localhost:8001}
      fallback: ${PAYMENT_SERVICE_URL_FALLBACK:http://localhost:8002}